# Generated by Django 4.2.20 on 2025-08-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者基本信息', 'verbose_name_plural': '患者基本信息'},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient_basic_info',
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='患者ID')),
                ('image_style', models.CharField(max_length=30, verbose_name='医学图像类别')),
                ('image', models.ImageField(upload_to='ct_images/%Y/%m/%d/', verbose_name='医学图像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.doctor', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '患者医学图像信息',
                'verbose_name_plural': '患者医学图像信息',
                'db_table': 'patient_image_info',
            },
        ),
    ]
