# Generated by Django 4.2.20 on 2025-08-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_image', models.ImageField(upload_to='xray_images/%Y/%m/%d/', verbose_name='X光图像')),
                ('segmentation_image', models.ImageField(upload_to='segmentation_results/%Y/%m/%d/', verbose_name='分割结果图像')),
                ('prompt_text', models.TextField(help_text='医生输入的分割提示文本，如"Bilateral pulmonary infection, two infected areas, all left lung and all right lung"', verbose_name='分割提示文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.doctor', verbose_name='创建医生')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='diagnosis.diagnosisresult', verbose_name='关联诊断结果')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='patient_records.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '分割结果',
                'verbose_name_plural': '分割结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
