# Generated by Django 4.2.20 on 2025-08-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('Normal', '无肺炎'), ('Mild', '轻度肺炎'), ('Severe', '重度肺炎')], max_length=20, verbose_name='诊断结果')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('probability_normal', models.FloatField(default=0.0, verbose_name='无肺炎概率')),
                ('probability_mild', models.FloatField(default=0.0, verbose_name='轻度肺炎概率')),
                ('probability_severe', models.FloatField(default=0.0, verbose_name='重度肺炎概率')),
                ('ct_image', models.ImageField(upload_to='ct_images/%Y/%m/%d/', verbose_name='CT图像')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='临床备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='诊断时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.doctor', verbose_name='创建医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_results', to='patient_records.patient')),
            ],
            options={
                'verbose_name': '诊断结果',
                'verbose_name_plural': '诊断结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
