# Generated by Django 4.2.20 on 2025-08-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_alter_patient_options_alter_patient_table_and_more'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneumonia_diagnosis_results', to='patient_records.patientinfo'),
        ),
        migrations.CreateModel(
            name='DiagResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=20, verbose_name='诊断结果标签')),
                ('confidence_0', models.FloatField(default=0.0, verbose_name='无外伤置信度')),
                ('confidence_1', models.FloatField(default=0.0, verbose_name='腹盆腔或腹膜后积血/血肿置信度')),
                ('confidence_2', models.FloatField(default=0.0, verbose_name='肝脏损伤置信度')),
                ('confidence_3', models.FloatField(default=0.0, verbose_name='脾脏损伤置信度')),
                ('confidence_4', models.FloatField(default=0.0, verbose_name='右肾损伤置信度')),
                ('confidence_5', models.FloatField(default=0.0, verbose_name='左肾损伤置信度')),
                ('confidence_6', models.FloatField(default=0.0, verbose_name='右肾上腺损伤置信度')),
                ('confidence_7', models.FloatField(default=0.0, verbose_name='胰腺损伤置信度')),
                ('image', models.ImageField(upload_to='ct_images/%Y/%m/%d/', verbose_name='CT图像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='诊断时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.doctor', verbose_name='创建医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diag_results', to='patient_records.patientinfo')),
            ],
            options={
                'verbose_name': '诊断结果',
                'verbose_name_plural': '诊断结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
