# Generated by Django 4.2.20 on 2025-08-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_diagnosisresult_patient_diagresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagresult',
            name='data_source',
            field=models.CharField(default='unknown', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='diagresult',
            name='data_source_label',
            field=models.CharField(default='未知数据源', max_length=50, verbose_name='数据来源标签'),
        ),
    ]
